---
title: "Multi-Analysis with Bayesian"
author: "Yicheng Shen"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
library(tidyverse)
library(lme4)
library(MASS)  
library(data.table)
library(Matrix)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
set.seed(123)

quiet_stan <- function(...) {
  con <- file(nullfile(), open = "wt")
  on.exit({
    try(sink(type = "message"), silent = TRUE)
    while (sink.number() > 0) try(sink(), silent = TRUE)
    try(close(con), silent = TRUE)
  }, add = TRUE)

  sink(con); sink(con, type = "message")  # silence stdout & messages
  suppressWarnings(                      # silence warnings
    suppressMessages(
      rstan::stan(..., refresh = 0, open_progress = FALSE, verbose = FALSE)
    )
  )
}
```


```{r}
# Parameters
H <- 3  # Number of sites
m_hosp <- sample(10:30, H, replace = TRUE)  # Number of patients per site
px <- 6  # Number of covariates
p_bin <- 3  # Number of binary covariates
p_cont <- px - p_bin  # Number of continuous covariates
py <- 3 # Number of outcomes (multivariate)

# Fixed effects
beta <- matrix(runif(px*py, -3, 3), nrow = px, ncol = py)  # Fixed effects for covariates

# Variance components
sigma_u <- 0.3  # Site-level variance
sigma_v_hosp <- runif(H, min = 0.5, max = 0.7)  # Varying sigma_v by hospital

# Exchangeable correlation structure
sigma_e <- 0.4  # Error variance
rho <- 0.5 # Correlation between outcomes
rho_mat <- matrix(rho, nrow = py, ncol = py)  # Exchangeable correlation matrix
diag(rho_mat) <- 1  # Diagonal elements are 1


# Generate data
nn <- rep(m_hosp, times = 1)  # Number of patients per hospital
id.hosp <- rep(1:H, times = m_hosp)  # Hospital ID
id.pat <- sequence(nn)  # Patient ID
n_visits <- sample(1:20, sum(nn), replace = TRUE)  # Number of visits per patient

# Expand hospital and patient IDs for visits
id.visit <- sequence(n_visits)
id.hosp.expanded <- rep(id.hosp, times = n_visits)
id.pat.expanded <- rep(id.pat, times = n_visits)

# Random effects
u_h <- rnorm(H, mean = 0, sd = sigma_u)  # Hospital effects
v_hi <- rnorm(sum(nn), mean = 0, sd = rep(sigma_v_hosp, times = m_hosp))  # Patient effects varying by hospital

# Expansion of hospital effects
u_h_patient <- rep(u_h, times = m_hosp)
u_h_expanded <- rep(u_h_patient, times = n_visits)

# Expansion of patient effects
v_hi_expanded <- rep(v_hi, times = n_visits)

# Covariates
X_bin <- matrix(rbinom(sum(n_visits) * p_bin, size = 1, prob = 0.3), nrow = sum(n_visits), ncol = p_bin)
X_cont <- matrix(rnorm(sum(n_visits) * p_cont, mean = 0, sd = 1), nrow = sum(n_visits), ncol = p_cont)
X_hij <- cbind(X_bin, X_cont)  # Combine binary & continuous covariates

# Generate multivariate errors with exchangeable correlation
epsilon_hij <- mvrnorm(sum(n_visits), mu = rep(0, py), 
                       Sigma = diag(sigma_e, py) %*% rho_mat %*% diag(sigma_e, py))

# Compute outcomes
Y_hij <- matrix(0, nrow = sum(n_visits), ncol = py)
for (k in 1:py) {
  Y_hij[, k] <- X_hij %*% beta[, k] + u_h_expanded + v_hi_expanded + epsilon_hij[, k]
}

# Create data table
three_lvl_dat <- data.table(
  site = id.hosp.expanded,
  patient = id.pat.expanded,
  visit = id.visit,
  X_hij, Y_hij
) %>% data.frame()

setnames(three_lvl_dat, c("site", "patient", "visit", paste0("X", 1:px), paste0("Y", 1:py)))

# Preprocessing
visit_count <- three_lvl_dat %>%
  dplyr::group_by(site, patient) %>%
  dplyr::summarise(total_visits = n(), .groups = "drop")

# Reorder data
rearranged_data <- merge(three_lvl_dat, visit_count, by = c("site", "patient")) %>%
  arrange(site, total_visits, patient) %>%
  mutate(site = factor(site))
```


# PEAL 

$$
\begin{aligned} 
\tilde X_h^\top \tilde X_h &= (R_\rho^{-1/2}\otimes X_h)^\top\,(R_\rho^{-1/2}\otimes X_h) \\ 
&= (R_\rho^{-1/2})^\top R_\rho^{-1/2}\ \otimes\ X_h^\top X_h \\ 
&= R_\rho^{-1}\ \otimes\ S_{h,XX}. 
\end{aligned}
$$


```{r}
source("../PEAL-Multivariate/PEAL_Engine_Multi-RI.R")
# XYZ
Y <- as.matrix(rearranged_data[, paste0("Y", 1:py)])
X <- as.matrix(rearranged_data[, paste0("X", 1:px)])
X <- cbind(X)
Z <- list()

for(i in 1:H){
  count_mat = rearranged_data %>%
                    filter(site == i) %>%
                    group_by(site, patient) %>%
                    dplyr::summarise(n_hi = n(), .groups = 'drop')

  Z[[i]] <- (generate_Zhv_matrix(count_mat))
}

id.site <- rearranged_data$site
```


```{r, eval = F}
peal.get.summary_mv(as.matrix(Y[,1]), X, Z, id.site = id.site, weights = NULL)[[1]]
peal.get.summary_mv(Y, X, Z, id.site = id.site, weights = NULL)[[1]]
```


```{r}
fit_mv_ind <- peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = TRUE,
  corstr = "independence",       
  estimate_rho = FALSE,
  verbose = TRUE
)


fit_mv <- peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = TRUE,
  corstr = "exchangeable",        # or "independence"
  estimate_rho = TRUE, rho_init = 0.1,  # estimate residual correlation
  verbose = TRUE
)
```

```{r}
c(beta) # true
fit_mv_ind$b
fit_mv$b

# fit_mv_ind$b.sd
# fit_mv$b.sd
```

```{r}
# Correlation
cat("true: ", rho, "\n")

cat("Indp: ", fit_mv_ind$rho, "\n")
 
cat("Exch: ", fit_mv$rho, "\n")
```

```{r}
# Residual
cat("true: ", sigma_e, "\n")

cat("Indp: ", sqrt(fit_mv_ind$s2), "\n")
 
cat("Exch: ", sqrt(fit_mv$s2), "\n")
```


```{r}
diag(sigma_e, py) %*% rho_mat %*% diag(sigma_e, py) # true
fit_mv$Sigma_e
```


```{r}
# RE
cat("true: ", c(sigma_u, sigma_v_hosp), "\n")

cat("Indp: ", sqrt(fit_mv_ind$theta * fit_mv_ind$s2), "\n")
 
cat("Exch: ", sqrt(fit_mv$theta * fit_mv$s2), "\n")
```


```{r, eval = F}
bench::mark(
  peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = T,
  corstr = "independence",       
  estimate_rho = F,
  verbose = T)
  )
bench::mark(
  peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = T,
  corstr = "exchangeable",       
  estimate_rho = T,
  verbose = T)
  )
```



```{r}
library(rstan)

dat <- rearranged_data %>%
  mutate(site = as.integer(factor(site)),
         pat  = as.integer(interaction(site, patient, drop = TRUE)))

N   <- nrow(dat)
H   <- length(unique(dat$site))
P   <- length(unique(dat$pat))
R   <- 3L
pX  <- 6L

y   <- as.matrix(dat[, paste0("Y", 1:R)])      # N x R
X   <- as.matrix(dat[, paste0("X", 1:pX)])     # N x pX
site_id <- dat$site                            # length N, in {1,...,H}
pat_id  <- dat$pat                             # length N, in {1,...,P}

# Map each patient to its site (needed to allow site-specific patient SDs)
pat_site <- dat %>%
  distinct(pat = pat_id, site = site_id) %>%
  arrange(pat) %>%
  pull(site)

stan_data <- list(
  N = N, H = H, P = P, R = R, p = pX,
  y = y, X = X, site_id = site_id, pat_id = pat_id, pat_site = pat_site
)
```


```{r}
options(mc.cores = parallelly::availableCores())
rstan_options(auto_write = TRUE)

fit_cs <- quiet_stan(
  file = "mv_lmm_cs.stan",
  data = stan_data,
  chains = 4, iter = 500, seed = 123,
  refresh = 0
)

print(fit_cs, pars = c("beta", "sigma_u", "sigma_v_h", "sigma_e", "rho"),
      probs = c(.025, .5, .975))

# Extract draws and produce tidy summaries:
post <- rstan::extract(fit_cs)

# Fixed effects (p x R):
beta_mean <- as.vector(apply(post$beta, R, colMeans))

# Variance components:
sigma_u_hat   <- mean(post$sigma_u)
sigma_vh_hat  <- apply(post$sigma_v_h, 2, mean)   # length H
sigma_e_hat   <- mean(post$sigma_e)
rho_hat       <- mean(post$rho)

list(
  beta_mean = beta_mean,
  sd_site = sigma_u_hat,
  sd_patient_by_site = sigma_vh_hat,
  sd_residual = sigma_e_hat,
  rho = rho_hat
)
```



```{r, eval=F}
library(shinystan)
launch_shinystan(fit_cs)
```



```{r}
options(mc.cores = parallelly::availableCores())
rstan_options(auto_write = TRUE)

fit_cs <- quiet_stan(
  file = "mv_lmm_cs_indep.stan",
  data = stan_data,
  chains = 4, iter = 500, seed = 123,
  refresh = 0
)

print(fit_cs, pars = c("beta", "sigma_u", "sigma_v_h", "sigma_e"),
      probs = c(.025, .5, .975))

# Extract draws and produce tidy summaries:
post <- rstan::extract(fit_cs)

# Fixed effects (p x R):
beta_mean <- as.vector(apply(post$beta, R, colMeans))

# Variance components:
sigma_u_hat   <- mean(post$sigma_u)
sigma_vh_hat  <- apply(post$sigma_v_h, 2, mean)   # length H
sigma_e_hat   <- mean(post$sigma_e)
rho_hat       <- mean(post$rho)

list(
  beta_mean = beta_mean,
  sd_site = sigma_u_hat,
  sd_patient_by_site = sigma_vh_hat,
  sd_residual = sigma_e_hat,
  rho = rho_hat
)
```