---
title: "Multi-Analysis"
author: "Yicheng Shen"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
rm(list = ls())
library(tidyverse)
library(lme4)
library(MASS)  
library(data.table)
library(Matrix)
library(mice)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
# set.seed(123)
source("MV-PEAL.R")
```


```{r}
# ---------------------------------------------------------
# Global Parameters
# ---------------------------------------------------------
H <- 5  # Number of sites
m_hosp <- sample(30:50, H, replace = TRUE)  # Number of patients per site
px <- 2  # Number of covariates
p_bin <- px/2  # Number of binary covariates
p_cont <- px - p_bin  # Number of continuous covariates
py <- 3 # Number of outcomes (multivariate)

# Fixed effects
beta <- matrix(seq(-10, 10, length.out = px * py), nrow = px, ncol = py)

# Variance components (Standard Deviations)
sigma_u <- 1 
sigma_v_hosp <-  seq(0.5, 0.7, length.out = H)
sigma_e <- 0.3

# UNSTRUCTURED Correlation Setup (3x3)
# Unique correlations: rho12, rho13, rho23
rho_true_vec <- c(0.2, 0.3, 0.7) # Ordered: (2,1), (3,1), (3,2)
Rho_mat <- diag(py)
Rho_mat[2,1] <- Rho_mat[1,2] <- rho_true_vec[1]
Rho_mat[3,1] <- Rho_mat[1,3] <- rho_true_vec[2]
Rho_mat[3,2] <- Rho_mat[2,3] <- rho_true_vec[3]

# Verify Positive Definiteness
if(min(eigen(Rho_mat)$values) <= 0) stop("Chosen correlation matrix is not positive definite.")
     
# --- 1. Data Generation ---
nn <- rep(m_hosp, times = 1) 
id.hosp <- rep(1:H, times = m_hosp)
id.pat <- sequence(nn)
n_visits <- sample(1:20, sum(nn), replace = TRUE) 

id.visit <- sequence(n_visits)
id.hosp.expanded <- rep(id.hosp, times = n_visits)
id.pat.expanded <- rep(id.pat, times = n_visits)

u_h <- rnorm(H, mean = 0, sd = sigma_u) 
u_h_expanded <- rep(rep(u_h, times = m_hosp), times = n_visits)

v_hi_mat <- matrix(0, nrow = sum(nn), ncol = py)
for(j in 1:py) {
  v_hi_mat[, j] <- rnorm(sum(nn), mean = 0, sd = rep(sigma_v_hosp, times = m_hosp))
}
v_hi_expanded_mat <- v_hi_mat[rep(1:nrow(v_hi_mat), times = n_visits), ]


X_bin <- matrix(rbinom(sum(n_visits) * p_bin, size = 1, prob = 0.3), nrow = sum(n_visits), ncol = p_bin)
X_cont <- matrix(rnorm(sum(n_visits) * p_cont, mean = 0, sd = 1), nrow = sum(n_visits), ncol = p_cont)
X_hij <- cbind(X_bin, X_cont) 

# Multivariate Errors with Unstructured Correlation
Sigma_err <- diag(sigma_e, py) %*% Rho_mat %*% diag(sigma_e, py)
epsilon_hij <- mvrnorm(sum(n_visits), mu = rep(0, py), Sigma = Sigma_err)

Y_hij <- matrix(0, nrow = sum(n_visits), ncol = py)
for (j in 1:py) {
 # Y_hij[, j] <- X_hij %*% beta[, j] + u_h_expanded + v_hi_expanded + epsilon_hij[, j]
  Y_hij[, j] <- X_hij %*% beta[, j] + u_h_expanded + v_hi_expanded_mat[, j] + epsilon_hij[, j]
}

three_lvl_dat <- data.frame(
 site = factor(id.hosp.expanded),
 patient = factor(id.pat.expanded),
 visit = id.visit,
 X_hij, Y_hij
)

visit_count <- three_lvl_dat %>%
 group_by(site, patient) %>%
 summarise(total_visits = n(), .groups = "drop")

rearranged_data <- merge(three_lvl_dat, visit_count, by = c("site","patient")) %>%
 arrange(site, total_visits, patient) %>%
 mutate(site = factor(site))

X_names <- paste0("X", 1:px)
Y_names <- paste0("Y", 1:py)
colnames(rearranged_data)[4:(4 + px - 1)] <- X_names
colnames(rearranged_data)[(4 + px):(4 + px + py - 1)] <- Y_names
```


```{r}
# -----------------------------------------------------
# 1.5 Generate MAR Missingness (Variable Levels per Y)
# -----------------------------------------------------
# Missingness depends on observed covariates X1 and X2.
rearranged_data_miss <- rearranged_data

# Define slopes (effect of covariates on missingness)
# These can remain constant or change if you want different dependencies
gamma_1 <- 0.5  # Effect of X1
gamma_2 <- 0.4  # Effect of X2

# Define different intercepts for Y1, Y2, Y3 to control their specific missingness levels
gamma_0_vec <- c(-2.5, -1.5, -0.5) 

# Iterate through columns using an index to access the specific gamma_0
for(j in seq_along(Y_names)){
  y_col <- Y_names[j]
  current_gamma_0 <- gamma_0_vec[j]
  
  # Calculate probability specifically for this column
  linear_pred <- current_gamma_0 + gamma_1 * rearranged_data$X1 + gamma_2 * rearranged_data$X2
  prob_miss <- 1 / (1 + exp(-linear_pred))
  
  # Apply missingness
  is_missing <- rbinom(n = nrow(rearranged_data), size = 1, prob = prob_miss)
  rearranged_data_miss[is_missing == 1, y_col] <- NA
}
```


```{r}
colMeans(is.na(rearranged_data_miss[, Y_names]))
sum(is.na(rearranged_data_miss[, Y_names]))/(nrow(rearranged_data_miss) * length(Y_names))
```



```{r}
# --- 2. Fit Model (Unstructured) ---
fit_mv <- peal.fit(
    data = rearranged_data,
    X_cols = X_names,
    Y_cols = Y_names,
    site_col = "site",
    patient_col = "patient",
    corstr = "unstructured",
    reml = TRUE,
    verbose = TRUE,
    use_rcpp = TRUE
  )

sigma_re_est <- sqrt(fit_mv$theta * fit_mv$s2)
sigma_e_est  <- sqrt(fit_mv$s2)
C_est <- fit_mv$Corr
rhos_est <- c(C_est[2, 1], C_est[3, 1], C_est[3, 2]) 

cbind(beta = c(beta), c(fit_mv$b))
cbind(sigma_u, sqrt(fit_mv$theta[1] * fit_mv$s2))
cbind(sigma_v_hosp, sqrt(fit_mv$theta[2:(H+1)] * fit_mv$s2))
cbind(sigma_e, sqrt(fit_mv$s2))
cbind(rho_true_vec, rhos_est)
```


```{r}
# --- 2. Fit Model (Unstructured) ---
fit_mv <- peal.fit(
    data = rearranged_data_miss,
    X_cols = X_names,
    Y_cols = Y_names,
    site_col = "site",
    patient_col = "patient",
    corstr = "unstructured",
    reml = TRUE,
    verbose = TRUE,
    use_rcpp = TRUE
  )

sigma_re_est <- sqrt(fit_mv$theta * fit_mv$s2)
sigma_e_est  <- sqrt(fit_mv$s2)
C_est <- fit_mv$Corr
rhos_est <- c(C_est[2, 1], C_est[3, 1], C_est[3, 2]) 

cbind(beta = c(beta), c(fit_mv$b))
cbind(sigma_u, sqrt(fit_mv$theta[1] * fit_mv$s2))
cbind(sigma_v_hosp, sqrt(fit_mv$theta[2:(H+1)] * fit_mv$s2))
cbind(sigma_e, sqrt(fit_mv$s2))
cbind(rho_true_vec, rhos_est)
```