---
title: "Multi-Analysis"
author: "Yicheng Shen"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
rm(list = ls())
library(tidyverse)
library(lme4)
library(MASS)  
library(data.table)
library(Matrix)
library(mice)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
# set.seed(123)
# source("MV-PEAL-RS.R")
```


```{r}
# ---------------------------------------------------------
# Full DGP: Multivariate 3-Level Model 
# Random Intercepts & Nested Random Slopes (Site + Patient)
# ---------------------------------------------------------
library(MASS)     
library(dplyr)   

# --- 1. Global Parameters ---
H <- 5            # Number of sites
m_hosp <- sample(50:70, H, replace = TRUE) # Patients per site
px <- 2           # Covariates (X1: Binary, X2: Continuous)
py <- 3           # Outcomes (Y1, Y2, Y3)

# Fixed effects matrix (px rows x py columns)
beta <- matrix(seq(-2, 2, length.out = px * py), nrow = px, ncol = py)

# Variance components (Standard Deviations)
sigma_u_int    <- 0.5   # Site intercept SD
sigma_v_int_vec   <- seq(0.5, 0.65, length.out = H) 
sigma_v_slope_vec <- seq(0.1, 0.2, length.out = H)
sigma_e        <- 0.2   # Residual SD

# --- 2. Unstructured Correlation Setup (Residuals) ---
rho_true_vec <- c(0.2, 0.3, 0.7) # (2,1), (3,1), (3,2)
Rho_mat <- diag(py)
Rho_mat[2,1] <- Rho_mat[1,2] <- rho_true_vec[1]
Rho_mat[3,1] <- Rho_mat[1,3] <- rho_true_vec[2]
Rho_mat[3,2] <- Rho_mat[2,3] <- rho_true_vec[3]

if(min(eigen(Rho_mat)$values) <= 0) stop("Correlation matrix not positive definite.")
Sigma_err <- diag(sigma_e, py) %*% Rho_mat %*% diag(sigma_e, py)

# --- 3. Build the Hierarchy ---
nn <- m_hosp
id.hosp <- rep(1:H, times = m_hosp)
id.pat  <- sequence(nn)
n_visits <- sample(1:10, sum(nn), replace = TRUE) 

# Expand IDs to Visit Level
id.visit <- sequence(n_visits)
id.hosp.expanded <- rep(id.hosp, times = n_visits)
id.pat.expanded  <- rep(id.pat, times = n_visits)
total_obs        <- sum(n_visits)

# --- 4. Generate Random Effects ---
# LEVEL 3: Site Effects (Intercept u and Slope w)
u_h <- rnorm(H, 0, sigma_u_int)

# LEVEL 2: Patient Effects (Intercept v and Slope z)
pat_site_id <- rep(1:H, times = m_hosp)
# Initialize matrices for Intercepts and Slopes
v_hi_mat <- matrix(0, nrow = sum(nn), ncol = py)
z_hi_mat <- matrix(0, nrow = sum(nn), ncol = py)

for(j in 1:py) {
  v_hi_mat[, j] <- rnorm(sum(nn), 
                         mean = 0, 
                         sd = sigma_v_int_vec[pat_site_id])
  
  z_hi_mat[, j] <- rnorm(sum(nn), 
                         mean = 0, 
                         sd = sigma_v_slope_vec[pat_site_id])
}

# --- 5. Generate Covariates (X) ---
X_bin  <- rbinom(total_obs, 1, 0.3)
X_cont <- rnorm(total_obs, 0, 1)
X_hij  <- cbind(X_bin, X_cont) # X[,2] is our continuous variable for the random slope

# --- 6. Assemble the Outcome (Y) ---
# Expand Site/Patient effects to match visit-level dimensions
u_h_exp <- rep(rep(u_h, times = m_hosp), times = n_visits)

# Indexing for patient-level expansion
pat_idx_exp <- rep(1:sum(nn), times = n_visits)
v_hi_exp <- v_hi_mat[pat_idx_exp, ]
z_hi_exp <- z_hi_mat[pat_idx_exp, ]

# Residuals
epsilon_hij <- mvrnorm(total_obs, mu = rep(0, py), Sigma = Sigma_err)

# Initialize Y matrix
Y_hij <- matrix(0, nrow = total_obs, ncol = py)

for (j in 1:py) {
  # The Formula:
  # Fixed(X*B) + Site_Int + Pat_Int_j + (Fixed_Slope_j + Site_Slope + Pat_Slope_j)*X2 + Error
  fixed_part  <- X_hij %*% beta[, j]
  intercepts  <- u_h_exp + v_hi_exp[, j]
  slopes_X2   <- (z_hi_exp[, j]) * X_hij[, 2]
  
  Y_hij[, j]  <- fixed_part + intercepts + slopes_X2 + epsilon_hij[, j]
}

# --- 7. Final Data Organization ---
three_lvl_dat <- data.frame(
  site    = factor(id.hosp.expanded),
  patient = factor(paste0(id.hosp.expanded, "_", id.pat.expanded)), # Unique IDs
  visit   = id.visit,
  X1      = X_hij[, 1],
  X2      = X_hij[, 2],
  Y1      = Y_hij[, 1],
  Y2      = Y_hij[, 2],
  Y3      = Y_hij[, 3]
)

visit_count <- three_lvl_dat %>%
 group_by(site, patient) %>%
 summarise(total_visits = n(), .groups = "drop")

rearranged_data <- merge(three_lvl_dat, visit_count, by = c("site","patient")) %>%
 arrange(site, total_visits, patient) %>%
 mutate(site = factor(site))

X_names <- paste0("X", 1:px)
Y_names <- paste0("Y", 1:py)
colnames(rearranged_data)[4:(4 + px - 1)] <- X_names
colnames(rearranged_data)[(4 + px):(4 + px + py - 1)] <- Y_names
```


```{r}
# -----------------------------------------------------
# 1.5 Generate MAR Missingness (Variable Levels per Y)
# -----------------------------------------------------
# Missingness depends on observed covariates X1 and X2.
rearranged_data_miss <- rearranged_data

# Define slopes (effect of covariates on missingness)
# These can remain constant or change if you want different dependencies
gamma_1 <- 0.5  # Effect of X1
gamma_2 <- 0.4  # Effect of X2

# Define different intercepts for Y1, Y2, Y3 to control their specific missingness levels
gamma_0_vec <- c(-2.5, -1.5, -0.5) 

# Iterate through columns using an index to access the specific gamma_0
for(j in seq_along(Y_names)){
  y_col <- Y_names[j]
  current_gamma_0 <- gamma_0_vec[j]
  
  # Calculate probability specifically for this column
  linear_pred <- current_gamma_0 + gamma_1 * rearranged_data$X1 + gamma_2 * rearranged_data$X2
  prob_miss <- 1 / (1 + exp(-linear_pred))
  
  # Apply missingness
  is_missing <- rbinom(n = nrow(rearranged_data), size = 1, prob = prob_miss)
  rearranged_data_miss[is_missing == 1, y_col] <- NA
}
```


```{r}
colMeans(is.na(rearranged_data_miss[, Y_names]))
sum(is.na(rearranged_data_miss[, Y_names]))/(nrow(rearranged_data_miss) * length(Y_names))
```

```{r}
source("MV-PEAL-RS2.R")
result <- peal.fit.rs(
  data = rearranged_data,
  X_cols = c("X1", "X2"), 
  Y_cols = c("Y1", "Y2", "Y3"),
  slope_col = "X2",        
  site_col = "site",
  patient_col = "patient",
  corstr = "unstructured"
)
# beta comparison
cbind("MV_PEAL beta" = c(result$beta), 
      "True beta" = c(beta))

cbind("MV_PEAL sigma_u" = c((result$sigma_site_int)), 
      "True sigma_u" = c(sigma_u_int))

cbind("MV_PEAL sigma_v_int" =c((result$sigma_pat_int)), 
      "MV_PEAL sigma_v_int" =c(sigma_v_int_vec))


cbind("MV_PEAL sigma_v_slope" =c((result$sigma_pat_slope)), 
      "True sigma_v_slope" =c(sigma_v_slope_vec))

cbind("MV_PEAL sigma_e" =c(sqrt(result$sigma2_residual)), 
      "True sigma_e" =c(sigma_e))

cbind("MV_PEAL R" =c((result$Corr)), 
      "True R" =c(Rho_mat))

result$time
result$opt$convergence
result$opt$message
```



```{r}
source("MV-PEAL-RS.R")
result <- peal.fit.rs(
  data = rearranged_data,
  X_cols = c("X1", "X2"), 
  Y_cols = c("Y1", "Y2", "Y3"),
  slope_col = "X2",        
  site_col = "site",
  patient_col = "patient",
  corstr = "unstructured"
)
# beta comparison
cbind("MV_PEAL beta" = c(result$beta), 
      "True beta" = c(beta))

cbind("MV_PEAL sigma_u" = c((result$sigma_site_int)), 
      "True sigma_u" = c(sigma_u_int))

cbind("MV_PEAL sigma_v_int" =c((result$sigma_pat_int)), 
      "MV_PEAL sigma_v_int" =c(sigma_v_int_vec))


cbind("MV_PEAL sigma_v_slope" =c((result$sigma_pat_slope)), 
      "True sigma_v_slope" =c(sigma_v_slope_vec))

cbind("MV_PEAL sigma_e" =c(sqrt(result$sigma2_residual)), 
      "True sigma_e" =c(sigma_e))

cbind("MV_PEAL R" =c((result$Corr)), 
      "True R" =c(Rho_mat))

result$time
```




```{r, eval = T}
source("MV-PEAL.R")
# --- 2. Fit Model (Unstructured) ---
fit_mv <- peal.fit(
    data = rearranged_data,
    X_cols = X_names,
    Y_cols = Y_names,
    site_col = "site",
    patient_col = "patient",
    corstr = "unstructured",
    reml = TRUE,
    verbose = TRUE,
    use_rcpp = TRUE
  )

sigma_re_est <- sqrt(fit_mv$theta * fit_mv$s2)
sigma_e_est  <- sqrt(fit_mv$s2)
C_est <- fit_mv$Corr
rhos_est <- c(C_est[2, 1], C_est[3, 1], C_est[3, 2]) 

cbind(beta = c(beta), c(fit_mv$b))
cbind(sigma_u_int, sqrt(fit_mv$theta[1] * fit_mv$s2))
cbind(sigma_v_int_vec, sqrt(fit_mv$theta[2:(H+1)] * fit_mv$s2))
cbind(sigma_e, sqrt(fit_mv$s2))
cbind(rho_true_vec, rhos_est)
fit_mv$time
```


```{r, eval = F}
# --- 2. Fit Model (Unstructured) ---
fit_mv <- peal.fit(
    data = rearranged_data_miss,
    X_cols = X_names,
    Y_cols = Y_names,
    site_col = "site",
    patient_col = "patient",
    corstr = "unstructured",
    reml = TRUE,
    verbose = TRUE,
    use_rcpp = TRUE
  )

sigma_re_est <- sqrt(fit_mv$theta * fit_mv$s2)
sigma_e_est  <- sqrt(fit_mv$s2)
C_est <- fit_mv$Corr
rhos_est <- c(C_est[2, 1], C_est[3, 1], C_est[3, 2]) 

cbind(beta = c(beta), c(fit_mv$b))
cbind(sigma_u_int, sqrt(fit_mv$theta[1] * fit_mv$s2))
cbind(sigma_v_int_vec, sqrt(fit_mv$theta[2:(H+1)] * fit_mv$s2))
cbind(sigma_e, sqrt(fit_mv$s2))
cbind(rho_true_vec, rhos_est)
```