---
title: "Multi-Analysis"
author: "Yicheng Shen"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
library(tidyverse)
library(lme4)
library(MASS)  
library(data.table)
library(Matrix)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
set.seed(123)
```


```{r}
# Parameters
H <- 3  # Number of sites
m_hosp <- sample(50:75, H, replace = TRUE)  # Number of patients per site
px <- 6  # Number of covariates
p_bin <- 3  # Number of binary covariates
p_cont <- px - p_bin  # Number of continuous covariates
py <- 3 # Number of outcomes (multivariate)

# Fixed effects
beta <- matrix(runif(px*py, -3, 3), nrow = px, ncol = py)  # Fixed effects for covariates

# Variance components
sigma_u <- 0.5  # Site-level variance
sigma_v_hosp <- runif(H, min = 0.5, max = 1)  # Varying sigma_v by hospital

# Exchangeable correlation structure
# --- Set pairwise correlations between outcomes (py = 3 here) ---
rho12 <- 0.40   # corr(Y1, Y2)
rho13 <- 0.20   # corr(Y1, Y3)
rho23 <- 0.60   # corr(Y2, Y3)

# Build 3x3 correlation matrix
corr_mat <- matrix(c(
  1,     rho12, rho13,
  rho12, 1,     rho23,
  rho13, rho23, 1
), nrow = py, ncol = py, byrow = TRUE)

# Ensure it's a valid correlation matrix (SPD with unit diagonal)
if (min(eigen(corr_mat, symmetric = TRUE, only.values = TRUE)$values) <= 0) {
  corr_mat <- as.matrix(nearPD(corr_mat, corr = TRUE)$mat)
}

# same residual SD for all outcomes, keep a scalar sigma_e:
sigma_e <- 0.3
sigma_e_vec <- rep(sigma_e, py)

# (Optional) If want outcome-specific residual SDs instead, set them here:
# sigma_e_vec <- c(0.4, 0.5, 0.35)  # example per-outcome SDs for Y1, Y2, Y3

De <- diag(sigma_e_vec, py)
Sigma_e <- De %*% corr_mat %*% De


# Generate data
nn <- rep(m_hosp, times = 1)  # Number of patients per hospital
id.hosp <- rep(1:H, times = m_hosp)  # Hospital ID
id.pat <- sequence(nn)  # Patient ID
n_visits <- sample(1:20, sum(nn), replace = TRUE)  # Number of visits per patient

# Expand hospital and patient IDs for visits
id.visit <- sequence(n_visits)
id.hosp.expanded <- rep(id.hosp, times = n_visits)
id.pat.expanded <- rep(id.pat, times = n_visits)

# Random effects
u_h <- rnorm(H, mean = 0, sd = sigma_u)  # Hospital effects
v_hi <- rnorm(sum(nn), mean = 0, sd = rep(sigma_v_hosp, times = m_hosp))  # Patient effects varying by hospital

# Expansion of hospital effects
u_h_patient <- rep(u_h, times = m_hosp)
u_h_expanded <- rep(u_h_patient, times = n_visits)

# Expansion of patient effects
v_hi_expanded <- rep(v_hi, times = n_visits)

# Covariates
X_bin <- matrix(rbinom(sum(n_visits) * p_bin, size = 1, prob = 0.3), nrow = sum(n_visits), ncol = p_bin)
X_cont <- matrix(rnorm(sum(n_visits) * p_cont, mean = 0, sd = 1), nrow = sum(n_visits), ncol = p_cont)
X_hij <- cbind(X_bin, X_cont)  # Combine binary & continuous covariates


# --- Generate multivariate residuals with non-exchangeable correlation ---
epsilon_hij <- mvrnorm(n = sum(n_visits), mu = rep(0, py), Sigma = Sigma_e)

# Compute outcomes
Y_hij <- matrix(0, nrow = sum(n_visits), ncol = py)
for (k in 1:py) {
  Y_hij[, k] <- X_hij %*% beta[, k] + u_h_expanded + v_hi_expanded + epsilon_hij[, k]
}

# Create data table
three_lvl_dat <- data.table(
  site = id.hosp.expanded,
  patient = id.pat.expanded,
  visit = id.visit,
  X_hij, Y_hij
) %>% data.frame()

setnames(three_lvl_dat, c("site", "patient", "visit", paste0("X", 1:px), paste0("Y", 1:py)))

# Preprocessing
visit_count <- three_lvl_dat %>%
  dplyr::group_by(site, patient) %>%
  dplyr::summarise(total_visits = n(), .groups = "drop")

# Reorder data
rearranged_data <- merge(three_lvl_dat, visit_count, by = c("site", "patient")) %>%
  arrange(site, total_visits, patient) %>%
  mutate(site = factor(site))
```



# PEAL 

$$
\begin{aligned} 
\tilde X_h^\top \tilde X_h &= (R_\rho^{-1/2}\otimes X_h)^\top\,(R_\rho^{-1/2}\otimes X_h) \\ 
&= (R_\rho^{-1/2})^\top R_\rho^{-1/2}\ \otimes\ X_h^\top X_h \\ 
&= R_\rho^{-1}\ \otimes\ S_{h,XX}. 
\end{aligned}
$$


```{r}
source("PEAL_Engine_Multi-RI_Rho.R")
# XYZ
Y <- as.matrix(rearranged_data[, paste0("Y", 1:py)])
X <- as.matrix(rearranged_data[, paste0("X", 1:px)])
X <- cbind(X)
Z <- list()

for(i in 1:H){
  count_mat = rearranged_data %>%
                    filter(site == i) %>%
                    group_by(site, patient) %>%
                    dplyr::summarise(n_hi = n(), .groups = 'drop')

  Z[[i]] <- (generate_Zhv_matrix(count_mat))
}

id.site <- rearranged_data$site
```


```{r, eval = F}
peal.get.summary_mv(as.matrix(Y[,1]), X, Z, id.site = id.site, weights = NULL)[[1]]
peal.get.summary_mv(Y, X, Z, id.site = id.site, weights = NULL)[[1]]
```


```{r}
fit_mv_ind <- peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = TRUE,
  corstr = "independence",       
  estimate_rho = FALSE,
  verbose = TRUE
)


fit_mv <- peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = TRUE,
  corstr = "exchangeable",        
  estimate_rho = TRUE, rho_init = 0.1,  # estimate residual correlation
  verbose = TRUE
)


fit_mv_unstr <- peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = TRUE,
  corstr = "unstructured",   # <--- new
  estimate_rho = TRUE,
  verbose = TRUE
)
```

```{r}
cbind(
c(beta), # true
fit_mv_ind$b,
fit_mv$b,
fit_mv_unstr$b)
```

```{r}
# Correlation
corr_mat
cat("Exch: ", fit_mv$rho, "\n")
fit_mv_unstr$Corr
```

```{r}
# Residual
cat("true: ", sigma_e, "\n")
cat("Indp: ", sqrt(fit_mv_ind$s2), "\n")
cat("Exch: ", sqrt(fit_mv$s2), "\n")
cat("Unstr: ", sqrt(fit_mv_unstr$s2), "\n")
```


```{r}
Sigma_e
fit_mv$Sigma_e
fit_mv_unstr$Sigma_e
```


```{r}
# RE
cat("true: ", c(sigma_u, sigma_v_hosp), "\n")

cat("Indp: ", sqrt(fit_mv_ind$theta * fit_mv_ind$s2), "\n")
 
cat("Exch: ", sqrt(fit_mv$theta * fit_mv$s2), "\n")

cat("Exch: ", sqrt(fit_mv_unstr$theta * fit_mv_unstr$s2), "\n")
```


```{r, eval = F}
bench::mark(
  peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = T,
  corstr = "independence",       
  estimate_rho = F,
  verbose = T)
  )
bench::mark(
  peal.fit.RI_mv(
  Y = Y, X = X, Z = Z, id.site = id.site,
  weights = NULL, reml = T,
  corstr = "exchangeable",       
  estimate_rho = T,
  verbose = T)
  )
```


