---
title: "Benchmark"
author: "Yicheng Shen"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
library(tidyverse)
library(lme4)
library(MASS)  
library(data.table)
library(gridExtra)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
source("DLMM_Engine_RI_P.R")
```


```{r}
##############################
# different site different patients

# Parameters
H <- 5  # of sites
m_hosp <- sample(100:200, H, replace = T) # of patients (1k to 3k later)


px <- 9  # of covariates
p_bin <- 5  # of binary X
p_cont <- px - p_bin  # of continuous X

beta <- c(2, 4, 6, 8, 10, 3, 5, 7, 9)  # Fixed effects for covariates

sigma_e <- 3  # error variance
sigma_u <- 3 # site-level variance
sigma_v_hosp <- runif(H, min = 1, max = 3)  # Varying sigma_v by hospital


# Generate data
nn <- rep(m_hosp, times = 1)  # Number of patients per hospital
id.hosp <- rep(1:H, times = m_hosp)   # Hospital ID
id.pat <- sequence(nn)                # Patient ID
n_visits <- sample(1:30, sum(nn), replace = TRUE)  # number of visits of patients

# Expand hospital and patient IDs for visits
id.visit <- sequence(n_visits)
id.hosp.expanded <- rep(id.hosp, times = n_visits)
id.pat.expanded <- rep(id.pat, times = n_visits)

# Random effects
u_h <- rnorm(H, mean = 0, sd = sigma_u)  # Hospital effects
v_hi <- rnorm(sum(nn), mean = 0, sd = rep(sigma_v_hosp, times = m_hosp))  # Patient effects varying by hospital

# Expansion of hospital effects
u_h_patient <- rep(u_h, times = m_hosp)
u_h_expanded <- rep(u_h_patient, times = n_visits)

# Expansion of patient effects
v_hi_expanded <- rep(v_hi, times = n_visits)

# covariates
X_bin <- matrix(rbinom(sum(n_visits) * p_bin, size = 1, prob = 0.3), nrow = sum(n_visits), ncol = p_bin)
X_cont <- matrix(rnorm(sum(n_visits) * p_cont, mean = 0, sd = 5), nrow = sum(n_visits), ncol = p_cont)
X_hij <- cbind(X_bin, X_cont)  # Combine binary & continuous covariates

epsilon_hij <- rnorm(sum(n_visits), mean = 0, sd = sigma_e)

# Compute outcome
y_hij <- X_hij %*% beta + u_h_expanded + v_hi_expanded + epsilon_hij

three_lvl_dat <- data.table(
  site = id.hosp.expanded,
  patient = id.pat.expanded,
  visit = id.visit,
  X_hij,
  Y = y_hij
) %>% data.frame() 

setnames(three_lvl_dat, c("site", "patient", "visit", paste0("X", 1:px), "Y"))


# Preprocessing
# Calculate the number of visits per patient per site
visit_count <- three_lvl_dat %>%
  dplyr::group_by(site, patient) %>%
  dplyr::summarise(total_visits = n(), .groups = "drop")

# Reorder data (as a preprocess probably)
rearranged_data <- merge(three_lvl_dat, visit_count, by = c("site", "patient")) %>%
  arrange(site, total_visits, patient) %>%
  mutate(site = factor(site))


# XYZ
Y <- rearranged_data$Y
X <- as.matrix(rearranged_data[, paste0("X", 1:px)])
X <- cbind(X)
Z <- list()

for(i in 1:H){
  count_mat = rearranged_data %>%
                    filter(site == i) %>%
                    group_by(site, patient) %>%
                    dplyr::summarise(n_hi = n(), .groups = 'drop')

  Z[[i]] <- (generate_Zhv_matrix(count_mat))
}

id.site <- rearranged_data$site

ShXYZ <- lmm.get.summary3(Y, X, Z, id.site)


# plot(density(Y), main = "Density of Y")
# plot(density(X[,9]), main = "Density of X9")
# lines(density(rnorm(1000, 0 , 5)))
```


```{r, eval = F}
source("DLMM_Engine_RI_P.R")
fit03.dlmm = lmm.fit3(Y = NULL, X = NULL, Z = NULL,
                      id.site = NULL, weights = NULL,
                      pooled = F, reml = T,
                      common.s2 = T,
                      ShXYZ = ShXYZ,  # only need summary stats
                      corstr = 'independence',
                      mypar.init = NULL)
fit03.dlmm$res.profile$lp

source("DLMM_Engine_RI_NP.R")
fit03.dlmm = lmm.fit3(Y = NULL, X = NULL, Z = NULL,
                      id.site = NULL, weights = NULL,
                      pooled = F, reml = T,
                      common.s2 = T,
                      ShXYZ = ShXYZ,  # only need summary stats
                      corstr = 'independence',
                      mypar.init = NULL)
fit03.dlmm$res.profile$lp
```



```{r}
source("DLMM_Engine_RI_P.R")
# source("DLMM_Engine_RI_NP.R")
fit03.dlmm = lmm.fit3(Y = NULL, X = NULL, Z = NULL,
                      id.site = NULL, weights = NULL,
                      pooled = F, reml = T,
                      common.s2 = T,
                      ShXYZ = ShXYZ,  # only need summary stats
                      corstr = 'independence',
                      mypar.init = NULL)
# fit03.dlmm$res.profile$lp
# fit03.dlmm$res
# fit03.dlmm$res.profile$allterms$qterm
# fit03.dlmm$s2p

est_beta = c(fit03.dlmm$b)
true_beta = c(beta)
cbind(est_beta, true_beta)


sqrt(fit03.dlmm$V)
sqrt(fit03.dlmm$s2)
est_sigma = c(sqrt(fit03.dlmm$V), sqrt(fit03.dlmm$s2))

true_sigma = c(sigma_u, sigma_v_hosp)
# true_sigma
# c(sigma_e)


plot(fit03.dlmm$b, true_beta)
abline(a = 0, b = 1, col = "blue", lwd = 2)

plot(sqrt(fit03.dlmm$V), true_sigma)
points(sqrt(fit03.dlmm$V)[1], true_sigma[1], col = "red")
abline(a = 0, b = 1, col = "blue", lwd = 2)
```

```{r, eval = T, warning=F}
three_lvl_dat$site = factor(three_lvl_dat$site)
three_lvl_dat$patient = factor(three_lvl_dat$patient)
three_lvl_dat$visit = factor(three_lvl_dat$visit)

model <- lmer(Y ~ -1 + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + 
              (1 | site) + (-1 + site || site: patient), 
              data = three_lvl_dat, control=lmerControl(optimizer = "optimx",
                                                        optCtrl  = list(method="L-BFGS-B")))

model_summ = summary(model)

fixed_effects <- fixef(model)
fixed_effects

vc <- VarCorr(model)
vc

random_effects = c(
sqrt(model_summ$varcor$site),
diag(sqrt(model_summ$varcor$`site:patient`)),
model_summ$sigma)

cbind(est_beta, fixed_effects, true_beta)
cbind(est_sigma, random_effects, true_sigma)
```


```{r}
fit03.dlmm$res
summary(model)
```


```{r, eval = F}
library(nlme)

# Fit model with hospital-specific patient variance
model_nlme <- lme(
  fixed = Y ~ -1 + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9,
  random = list(site = ~ 1, patient = ~ 1),  # patient nested in site
  weights = varIdent(form = ~ 1 | site),     # different residual variance per site
  data = three_lvl_dat
)

# Check variance estimates
VarCorr(model_nlme)
```



```{r, eval = F}
library(brms)

# Fit model with hospital-specific patient variance
model_brms <- brm(
  Y ~ -1 + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + 
    (1 | site) + (site | site:patient),
  # prior = set_prior("normal(0, 5)"),  # Weakly informative priors
  data = three_lvl_dat,
  chains = 2, iter = 5000  # Short MCMC for demonstration
)

# Extract variance components
# plot(model_brms)
summary(model_brms)
ranef(model_brms)  # Random effects per site/patient
```






```{r}
source("DLMM_Engine_RI_P.R")
bench::mark(fit03.dlmm = lmm.fit3(Y = NULL, X = NULL, Z = NULL,
                      id.site = NULL, weights = NULL,
                      pooled = F, reml = T,
                      common.s2 = T,
                      ShXYZ = ShXYZ,  # only need summary stats
                      corstr = 'independence',
                      mypar.init = NULL))
source("DLMM_Engine_RI_NP.R")
bench::mark(fit03.dlmm = lmm.fit3(Y = NULL, X = NULL, Z = NULL,
                      id.site = NULL, weights = NULL,
                      pooled = F, reml = T,
                      common.s2 = T,
                      ShXYZ = ShXYZ,  # only need summary stats
                      corstr = 'independence',
                      mypar.init = NULL))
```

