---
title: "Benchmark"
author: "Yicheng Shen"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
library(tidyverse)
library(lme4)
library(splines)
library(MASS)  
library(data.table)
library(gridExtra)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
source("DLMM_Engine_RI_P2.R")
```


```{r, warning=F}
##############################
# different site different patients

# Parameters
H <- 5  # of sites
m_hosp <- sample(50:100, H, replace = T) # of patients (1k to 3k later)


px <- 9  # of covariates
p_bin <- 5  # of binary X
p_cont <- px - p_bin  # of continuous X

beta <- c(2, 4, 6, 8, 10, 3, 5, 7, 9)  # Fixed effects for covariates

sigma_e <- 2  # error variance
sigma_u <- 3 # site-level variance
sigma_v_hosp <- runif(H, min = 1, max = 5)  # Varying sigma_v by hospital


# Generate data
nn <- rep(m_hosp, times = 1)  # Number of patients per hospital
id.hosp <- rep(1:H, times = m_hosp)   # Hospital ID
id.pat <- sequence(nn)                # Patient ID
n_visits <- sample(1:30, sum(nn), replace = TRUE)  # number of visits of patients

# Expand hospital and patient IDs for visits
id.visit <- sequence(n_visits)
id.hosp.expanded <- rep(id.hosp, times = n_visits)
id.pat.expanded <- rep(id.pat, times = n_visits)

# Random effects
u_h <- rnorm(H, mean = 0, sd = sigma_u)  # Hospital effects
v_hi <- rnorm(sum(nn), mean = 0, sd = rep(sigma_v_hosp, times = m_hosp))  # Patient effects varying by hospital

# Expansion of hospital effects
u_h_patient <- rep(u_h, times = m_hosp)
u_h_expanded <- rep(u_h_patient, times = n_visits)

# Expansion of patient effects
v_hi_expanded <- rep(v_hi, times = n_visits)

# covariates
X_bin <- matrix(rbinom(sum(n_visits) * p_bin, size = 1, prob = 0.3), nrow = sum(n_visits), ncol = p_bin)
X_cont <- matrix(rnorm(sum(n_visits) * p_cont, mean = 0, sd = 5), nrow = sum(n_visits), ncol = p_cont)
X_hij <- cbind(X_bin, X_cont)  # Combine binary & continuous covariates

epsilon_hij <- rnorm(sum(n_visits), mean = 0, sd = sigma_e)

# Compute outcome
y_hij <- X_hij %*% beta + u_h_expanded + v_hi_expanded + epsilon_hij

three_lvl_dat <- data.table(
  site = id.hosp.expanded,
  patient = id.pat.expanded,
  visit = id.visit,
  X_hij,
  Y = y_hij
) %>% data.frame() 

setnames(three_lvl_dat, c("site", "patient", "visit", paste0("X", 1:px), "Y"))


# Add a time variable (e.g., visit time)
three_lvl_dat <- three_lvl_dat %>%
  group_by(site, patient) %>%
  mutate(
    delta_t = ifelse(visit == 1, 0, rpois(n(), lambda = 7)),   # Poisson 7 (every week?)
    visit_time = ifelse(visit == 1, 0, cumsum(delta_t))        # Cumulative time since first visit
  ) %>%
  ungroup() %>%
  mutate(
    time_effect = 0.5 * visit_time - 0.03 * (visit_time)^2,
    # time_effect = cos(visit_time),
    Y = Y + time_effect  # Add to existing outcome
  )
```



```{r, eval = F, warning=F}
three_lvl_dat %>% filter(site == 1) %>% mutate(patient = factor(patient)) %>%
  ggplot(aes(x = X9, y = Y, colour = patient, group = patient)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(se = F, size = .3, method = "lm") + 
  geom_smooth(aes(X9, Y, group = 1), se = F, size = 2, col = "BlACK") + 
  theme(legend.position = "none")

three_lvl_dat %>% mutate(patient = factor(patient)) %>% 
  filter(site == 1) %>% group_by(patient) %>% 
  ggplot(aes(x = visit_time, y = Y, colour = patient, group = patient)) +
  geom_point(alpha = 0.5) + 
  geom_smooth(se = F, size = .3) + labs(x = "Visit Time") + 
  geom_smooth(aes(visit_time, Y, group = 1), se = F) + theme(legend.position = "none")

plot(density(three_lvl_dat$Y))
```

```{r}
three_lvl_dat %>% 
  mutate(site = factor(site)) %>% 
  ggplot(aes(visit_time, fill = site)) + geom_histogram() + facet_wrap(~site) + 
  labs(x = "Visit Time") + theme(legend.position = "none")

three_lvl_dat %>% 
  mutate(site = factor(site)) %>% 
  ggplot(aes(visit_time, col = 5, fill = site, group = site)) + geom_histogram()  + 
  labs(x = "Visit Time") + theme(legend.position = "none")
   
knots <- quantile(three_lvl_dat$visit_time, probs = c(0.25, 0.5, 0.75))
# seq(0.1, 0.9, length.out = 5)
```




```{r}
compute_site_histograms <- function(df, bin_edges) {
    h <- hist(df$visit_time, 
              breaks = seq(0, 300, length.out = bin_edges), 
              plot = FALSE)
    return(list(counts = h$counts, bin_edges = h$breaks))
}

bin_edges = 50
site_histogram1 = compute_site_histograms(three_lvl_dat[three_lvl_dat$site == 1,], bin_edges)
site_histogram2 = compute_site_histograms(three_lvl_dat[three_lvl_dat$site == 2,], bin_edges)
site_histogram3 = compute_site_histograms(three_lvl_dat[three_lvl_dat$site == 3,], bin_edges)
site_histogram4 = compute_site_histograms(three_lvl_dat[three_lvl_dat$site == 4,], bin_edges)
site_histogram5 = compute_site_histograms(three_lvl_dat[three_lvl_dat$site == 5,], bin_edges)

site_histograms = list(site_histogram1, site_histogram2, site_histogram3, site_histogram4, site_histogram5)

all_edges <- lapply(site_histograms, function(h) h$bin_edges)
all_counts <- lapply(site_histograms, function(h) h$counts)
global_counts <- Reduce(`+`, all_counts)

# Compute quantiles from aggregated counts
bin_midpoints <- (all_edges[[1]][-1] + all_edges[[1]][-length(all_edges[[1]])]) / 2
ecdf <- cumsum(global_counts) / sum(global_counts)

find_quantile <- function(p) {
  idx <- max(which(ecdf <= p))
  if (idx == length(ecdf)) return(all_edges[[1]][length(all_edges[[1]])])
  if (idx == 0) return(all_edges[[1]][1])
  
  p_low <- ifelse(idx == 0, 0, ecdf[idx])
  p_high <- ecdf[idx + 1]
  w <- (p - p_low) / (p_high - p_low)
  bin_midpoints[idx] + w * (bin_midpoints[idx + 1] - bin_midpoints[idx])
}

quantiles <- c("0.25" = find_quantile(0.25), "0.5" = find_quantile(0.5), "0.75" = find_quantile(0.75))

list(
  global_counts = global_counts,
  bin_edges = all_edges[[1]],
  quantiles = quantiles
)
```

```{r}
quantile(three_lvl_dat$visit_time, probs = c(0.25, 0.5, 0.75))
```


```{r}
knots = quantiles
```


```{r}
# Preprocessing
# Calculate the number of visits per patient per site
visit_count <- three_lvl_dat %>%
  dplyr::group_by(site, patient) %>%
  dplyr::summarise(total_visits = n(), .groups = "drop")

# Reorder data
rearranged_data <- merge(three_lvl_dat, visit_count, by = c("site", "patient")) %>%
  arrange(site, total_visits, patient) %>%
  mutate(site = factor(site))


# XYZ
Y <- rearranged_data$Y 
X <- as.matrix(rearranged_data[, paste0("X", 1:px)])
T_ns = ns(rearranged_data$visit_time, knots = knots) %>% as.matrix()
X <- cbind(X, T_ns)
Z <- list()



for(i in 1:H){
  count_mat = rearranged_data %>%
                    filter(site == i) %>%
                    group_by(site, patient) %>%
                    dplyr::summarise(n_hi = n(), .groups = 'drop')

  Z[[i]] <- (generate_Zhv_matrix(count_mat))
}

id.site <- rearranged_data$site

ShXYZ <- lmm.get.summary3(Y, X, Z, id.site)
```



```{r}
source("DLMM_Engine_RI_P2.R")
fit03.dlmm = lmm.fit3(Y = NULL, X = NULL, Z = NULL,
                      id.site = NULL, weights = NULL,
                      pooled = F, reml = T,
                      common.s2 = T,
                      ShXYZ = ShXYZ,  # only need summary stats
                      corstr = 'independence',
                      mypar.init = NULL)

dlmm_beta = c(fit03.dlmm$b[1:px])
true_beta = c(beta)
cbind(est_beta, true_beta)

dlmm_spline = fit03.dlmm$b[-c(1:px)]


sqrt(fit03.dlmm$V)
sqrt(fit03.dlmm$s2)
dlmm_sigma = c(sqrt(fit03.dlmm$V), sqrt(fit03.dlmm$s2))

true_sigma = c(sigma_u, sigma_v_hosp, sigma_e)
cbind(dlmm_sigma, true_sigma)


plot(dlmm_beta, true_beta)
abline(a = 0, b = 1, col = "blue", lwd = 2)

plot(dlmm_sigma, true_sigma)
points(dlmm_sigma[1], true_sigma[1], col = "red")
abline(a = 0, b = 1, col = "blue", lwd = 2)
```


```{r, warning=F}
three_lvl_dat$site = factor(three_lvl_dat$site)
three_lvl_dat$patient = factor(three_lvl_dat$patient)
three_lvl_dat$visit = factor(three_lvl_dat$visit)

# Fit with natural cubic spline for time
model <- lmer(Y ~ -1 + X1 + X2 + X3 + X4 + X5 + X6 + X7 + X8 + X9 + 
              ns(visit_time, knots = knots) +      # Spline for time
              (1 | site) + (-1 + site || site: patient), 
              data = three_lvl_dat, control=lmerControl(optimizer = "optimx",
                                                        optCtrl  = list(method="L-BFGS-B")))

model_summ = summary(model)

lmer_beta <- fixef(model)[1:px]
lmer_spline <- fixef(model)[-c(1:px)]

vc <- VarCorr(model)

lmer_sigma = c(
sqrt(model_summ$varcor$site),
diag(sqrt(model_summ$varcor$`site:patient`)),
model_summ$sigma)
```

```{r}
cbind(dlmm_beta, lmer_beta, true_beta)
cbind(dlmm_sigma, lmer_sigma, true_sigma)
cbind(dlmm_spline, lmer_spline)
```


```{r}
cbind(dlmm_beta, fit03.dlmm$lb[1:px], fit03.dlmm$ub[1:px])
fit03.dlmm$b.sd
summary(model)
```

